// Prism — export disclosure fixtures to Rust for the disclosure contract test.
import { readFileSync, writeFileSync } from "node:fs";

const dir = new URL("../fixtures/disclosure/", import.meta.url);
const vk = JSON.parse(readFileSync(new URL("verification_key.json", dir)));
const proof = JSON.parse(readFileSync(new URL("proof.json", dir)));
const meta = JSON.parse(readFileSync(new URL("meta.json", dir)));

const to32 = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const g1 = (p) => to32(p[0]) + to32(p[1]);
const g2 = (p) => to32(p[0][1]) + to32(p[0][0]) + to32(p[1][1]) + to32(p[1][0]);
const bytes = (hex) => `[${hex.match(/../g).map((b) => `0x${b}`).join(", ")}]`;
const a1 = (name, hex) => `pub const ${name}: [u8; ${hex.length / 2}] = ${bytes(hex)};`;
const aN = (name, len, hexes) =>
  `pub const ${name}: [[u8; ${len}]; ${hexes.length}] = [\n${hexes
    .map((h) => `    ${bytes(h)}`)
    .join(",\n")},\n];`;

const out = `// @generated by circuits/scripts/export_disclosure_fixtures_rs.mjs — DO NOT EDIT.
#![allow(dead_code, clippy::all)]

${a1("VK_ALPHA", g1(vk.vk_alpha_1))}
${a1("VK_BETA", g2(vk.vk_beta_2))}
${a1("VK_GAMMA", g2(vk.vk_gamma_2))}
${a1("VK_DELTA", g2(vk.vk_delta_2))}
${aN("VK_IC", 64, vk.IC.map(g1))}

${a1("PROOF_A", g1(proof.pi_a))}
${a1("PROOF_B", g2(proof.pi_b))}
${a1("PROOF_C", g1(proof.pi_c))}

// public signals: [commitment, Ax, Ay, Rx, Ry, c]
${a1("COMMITMENT", to32(meta.commitment))}
${a1("AX", to32(meta.Ax))}
${a1("AY", to32(meta.Ay))}
${a1("RX", to32(meta.Rx))}
${a1("RY", to32(meta.Ry))}
${a1("CIPHERTEXT", to32(meta.c))}
${a1("AMOUNT", to32(meta.amount))}
`;

writeFileSync(new URL("../../contracts/disclosure/src/disclosure_fixtures.rs", import.meta.url), out);
console.error("wrote contracts/disclosure/src/disclosure_fixtures.rs (IC len:", vk.IC.length, ")");
