// Prism — convert snarkjs Groth16/BN254 fixtures into a Rust source file of raw
// byte arrays for the Soroban verifier test.
//
// Encodings (Ethereum / EIP-196-197 compatible, as required by soroban-sdk Bn254):
//   G1  (64 bytes): be32(X) || be32(Y)
//   G2 (128 bytes): be32(X.c1) || be32(X.c0) || be32(Y.c1) || be32(Y.c0)   (imaginary first)
//   Fr  (32 bytes): be32(scalar)
// snarkjs stores Fp2 as [c0, c1]; the host wants c1 (imaginary) first, matching
// the snarkjs-generated Solidity verifier's coordinate swap.
import { readFileSync, writeFileSync } from "node:fs";

const dir = new URL("../fixtures/", import.meta.url);
const vk = JSON.parse(readFileSync(new URL("verification_key.json", dir)));
const proof = JSON.parse(readFileSync(new URL("proof.json", dir)));
const pub = JSON.parse(readFileSync(new URL("public.json", dir)));

const to32 = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const g1 = (p) => to32(p[0]) + to32(p[1]);
const g2 = (p) => to32(p[0][1]) + to32(p[0][0]) + to32(p[1][1]) + to32(p[1][0]);

const arr = (name, hex) => {
  const bytes = hex.match(/../g).map((b) => `0x${b}`).join(", ");
  return `pub const ${name}: [u8; ${hex.length / 2}] = [${bytes}];`;
};
const arrOfArr = (name, len, hexes) => {
  const inner = hexes
    .map((h) => `    [${h.match(/../g).map((b) => `0x${b}`).join(", ")}]`)
    .join(",\n");
  return `pub const ${name}: [[u8; ${len}]; ${hexes.length}] = [\n${inner},\n];`;
};

const lines = [
  "// @generated by circuits/scripts/export_fixtures_rs.mjs — DO NOT EDIT.",
  "// Groth16/BN254 fixtures for membership.circom (4 public signals).",
  "#![allow(clippy::all)]",
  "",
  arr("VK_ALPHA", g1(vk.vk_alpha_1)),
  arr("VK_BETA", g2(vk.vk_beta_2)),
  arr("VK_GAMMA", g2(vk.vk_gamma_2)),
  arr("VK_DELTA", g2(vk.vk_delta_2)),
  arrOfArr("VK_IC", 64, vk.IC.map(g1)),
  "",
  arr("PROOF_A", g1(proof.pi_a)),
  arr("PROOF_B", g2(proof.pi_b)),
  arr("PROOF_C", g1(proof.pi_c)),
  "",
  arrOfArr("PUB_SIGNALS", 32, pub.map(to32)),
  "",
];

const out = new URL(
  "../../contracts/verifier-registry/src/test_fixtures.rs",
  import.meta.url,
);
writeFileSync(out, lines.join("\n"));
console.error(`wrote ${out.pathname}`);
console.error(`IC points: ${vk.IC.length}, public signals: ${pub.length}, nPublic: ${vk.nPublic}`);
