// Prism — export aggregation fixtures (K in {1,2,4,8}) to a Rust module the Aggregator
// contract test/bench consumes. Same point encodings as the day-1 exporter:
//   G1=be(X)||be(Y) (64), G2=be(X.c1)||be(X.c0)||be(Y.c1)||be(Y.c0) (128), Fr=be(scalar) (32).
import { readFileSync, writeFileSync } from "node:fs";

const KS = [1, 2, 4, 8];
const root = new URL("../fixtures/", import.meta.url);

const to32 = (dec) => BigInt(dec).toString(16).padStart(64, "0");
const g1 = (p) => to32(p[0]) + to32(p[1]);
const g2 = (p) => to32(p[0][1]) + to32(p[0][0]) + to32(p[1][1]) + to32(p[1][0]);
const bytes = (hex) => `[${hex.match(/../g).map((b) => `0x${b}`).join(", ")}]`;
const arr1 = (name, hex) => `    pub const ${name}: [u8; ${hex.length / 2}] = ${bytes(hex)};`;
const arrN = (name, len, hexes) =>
  `    pub const ${name}: [[u8; ${len}]; ${hexes.length}] = [\n${hexes
    .map((h) => `        ${bytes(h)}`)
    .join(",\n")},\n    ];`;

let out = `// @generated by circuits/scripts/export_agg_fixtures_rs.mjs — DO NOT EDIT.
#![allow(dead_code, clippy::all)]
`;

for (const K of KS) {
  const dir = new URL(`agg_k${K}/`, root);
  const vk = JSON.parse(readFileSync(new URL("verification_key.json", dir)));
  const proof = JSON.parse(readFileSync(new URL("proof.json", dir)));
  const meta = JSON.parse(readFileSync(new URL("meta.json", dir)));

  out += `
pub mod k${K} {
    pub const K: u32 = ${K};
${arr1("VK_ALPHA", g1(vk.vk_alpha_1))}
${arr1("VK_BETA", g2(vk.vk_beta_2))}
${arr1("VK_GAMMA", g2(vk.vk_gamma_2))}
${arr1("VK_DELTA", g2(vk.vk_delta_2))}
${arrN("VK_IC", 64, vk.IC.map(g1))}
${arr1("PROOF_A", g1(proof.pi_a))}
${arr1("PROOF_B", g2(proof.pi_b))}
${arr1("PROOF_C", g1(proof.pi_c))}
${arr1("ROOT", to32(meta.root))}
${arr1("EXT_NULL", to32(meta.externalNullifier))}
${arr1("H", to32(meta.H))}
${arr1("AGG_OUTPUT", to32(meta.aggregateOutput))}
${arrN("NULLIFIERS", 32, meta.nullifiers.map(to32))}
${arrN("COMMITMENTS", 32, meta.commitments.map(to32))}
}
`;
}

const dst = new URL("../../contracts/aggregator/src/agg_fixtures.rs", import.meta.url);
writeFileSync(dst, out);
console.error(`wrote ${dst.pathname} for K=${KS.join(",")}`);
