// Prism — export circomlib Poseidon (BN254) t=3 constants to Rust so the on-chain
// `poseidon_permutation` host call reproduces circomlib's hash exactly.
//
// circomlib reference (poseidon_reference.js): t = nInputs+1, state=[0,...inputs],
// per round r: state[i] += C[t-2][r*t+i]; sbox (x^5) full or partial; state = M[t-2]·state.
// We only need t=3 on-chain (Merkle, commitment, nullifier, and the H-fold are all 2-input).
import { writeFileSync } from "node:fs";

const consts = (await import(new URL("../node_modules/circomlibjs/src/poseidon_constants.js", import.meta.url).href)).default;
const T = 3;
const C = consts.C[T - 2]; // flat, length rounds*T
const M = consts.M[T - 2]; // T x T
const ROUNDS_F = 8;
const ROUNDS_P = [56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68][T - 2];
const rounds = ROUNDS_F + ROUNDS_P;
if (C.length !== rounds * T) throw new Error(`C len ${C.length} != ${rounds * T}`);

const to32 = (x) => BigInt(x).toString(16).padStart(64, "0");
const arr = (hex) => `[${hex.match(/../g).map((b) => `0x${b}`).join(", ")}]`;

const rcLines = C.map((x) => `    ${arr(to32(x))}`).join(",\n");
const mdsFlat = [];
for (let i = 0; i < T; i++) for (let j = 0; j < T; j++) mdsFlat.push(M[i][j]);
const mdsLines = mdsFlat.map((x) => `    ${arr(to32(x))}`).join(",\n");

const out = `// @generated by circuits/scripts/export_poseidon_consts_rs.mjs — DO NOT EDIT.
// circomlib Poseidon (BN254) constants for t=3 (2-input hash).
#![allow(clippy::all)]

pub const T: u32 = ${T};
pub const D: u32 = 5;
pub const ROUNDS_F: u32 = ${ROUNDS_F};
pub const ROUNDS_P: u32 = ${ROUNDS_P};

/// Round constants, row-major (r*T + i), length (ROUNDS_F+ROUNDS_P)*T.
pub const RC: [[u8; 32]; ${C.length}] = [
${rcLines},
];

/// MDS matrix, row-major (i*T + j), length T*T.
pub const MDS: [[u8; 32]; ${mdsFlat.length}] = [
${mdsLines},
];
`;

const dst = new URL("../../contracts/poseidon/src/constants_t3.rs", import.meta.url);
writeFileSync(dst, out);
console.error(`wrote ${dst.pathname} (RC=${C.length}, MDS=${mdsFlat.length}, rounds=${rounds})`);
